# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
{{- if ne (.Values.prometheusRules.ruleGroups.netappNvdimmAlerts | toString) "false" }}
groups:
  - name: netapp_nvdimm_alerts
    rules:
      - alert: NVdimmECCErrors
        expr: (ems_events{message="callhome.nvdimm.cecc"})
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "sci-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_nvdimm
        annotations:
          summary: This event occurs when excessive correctable ECC memory errors are reported by the NVDIMM (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            NVDIMM ECC Errors
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

      - alert: NVMemBatteryLow
        expr: (ems_events{message="monitor.nvmembattery.warninglow"})
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "sci-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_nvdimm
        annotations:
          summary: This message occurs when the NVMEM battery charge is low (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            NVMEM Battery Low
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

      - alert: NVRAMBatteryLow
        expr: (ems_events{message="monitor.nvramLowBattery.notice"})
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "sci-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_nvdimm
        annotations:
          summary: This message occurs when the NVRAM battery is dangerously low (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            NVRAM Battery Low
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}
{{- else }}
groups: []
{{- end }}
