# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
{{- $anyEnabled := (ne (.Values.prometheusRules.ruleGroups.netappAggrAlerts | toString) "false") }}
{{- if not $anyEnabled }}
groups: []
{{- else }}
groups:
{{- if ne (.Values.prometheusRules.ruleGroups.netappAggrAlerts | toString) "false" }}
  - name: netapp_aggr_alerts
    rules:
{{- if not (index .Values.prometheusRules.disabled "AggrNearlyFull" | default false) }}
      - alert: AggrNearlyFull
        expr: (avg_over_time(aggr_space_physical_used_percent{netapp_cluster=~"stnpc.*"}[2h])) > 70
        for: 5m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate nearly full (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate used space > 70%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- if not (index .Values.prometheusRules.disabled "AggrFull" | default false) }}
      - alert: AggrFull
        expr: (avg_over_time(aggr_space_physical_used_percent{netapp_cluster=~"stnpc.*"}[2h])) > 80
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate full (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate used space > 80%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- if not (index .Values.prometheusRules.disabled "AggrNearlyFullbrazilstorec2" | default false) }}
      - alert: AggrNearlyFullbrazilstorec2
        expr: (avg_over_time(aggr_space_physical_used_percent{netapp_cluster="brazilstorec2"}[2h])) > 90
        for: 5m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate nearly full (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate used space > 90%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- if not (index .Values.prometheusRules.disabled "AggrFullbrazilstorec2" | default false) }}
      - alert: AggrFullbrazilstorec2
        expr: (avg_over_time(aggr_space_physical_used_percent{netapp_cluster="brazilstorec2"}[2h])) > 95
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate full (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate used space > 95%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- if not (index .Values.prometheusRules.disabled "AggrNearlyFullHEC" | default false) }}
      - alert: AggrNearlyFullHEC
        expr: (avg_over_time(aggr_space_physical_used_percent{netapp_cluster!="hec03fc005"}[2h])) > 95
        for: 5m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate nearly full (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate used space > 95%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- if not (index .Values.prometheusRules.disabled "AggrFullHEC" | default false) }}
      - alert: AggrFullHEC
        expr: (avg_over_time(aggr_space_physical_used_percent{netapp_cluster!="hec03fc005"}[2h])) > 90
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate full (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate used space > 90%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- if not (index .Values.prometheusRules.disabled "AggrNearlyFullHEC03FC005" | default false) }}
      - alert: AggrNearlyFullHEC03FC005
        expr: (avg_over_time(aggr_space_physical_used_percent{netapp_cluster="hec03fc005"}[2h])) > 85
        for: 5m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate full (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate used space > 85%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- if not (index .Values.prometheusRules.disabled "AggrFullHEC03FC005" | default false) }}
      - alert: AggrFullHEC03FC005
        expr: (avg_over_time(aggr_space_physical_used_percent{netapp_cluster="hec03fc005"}[2h])) > 90
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate full (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate used space > 90%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- if not (index .Values.prometheusRules.disabled "AggrNearlyFullInternal" | default false) }}
      - alert: AggrNearlyFullInternal
        expr: (avg_over_time(aggr_space_physical_used_percent{netapp_cluster!="derotnpc001",netapp_cluster!="derotnpc0013",netapp_cluster!~"hec.*",netapp_cluster!~"stnpca.*",netapp_cluster!="brazilstorec2",aggr!="aggr_sata_sl_00103"}[2h])) > 85
        for: 5m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate full (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate used space > 85%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- if not (index .Values.prometheusRules.disabled "AggrFullInternal" | default false) }}
      - alert: AggrFullInternal
        expr: (avg_over_time(aggr_space_physical_used_percent{netapp_cluster!="derotnpc001",netapp_cluster!="derotnpc0013",netapp_cluster!~"hec.*",netapp_cluster!~"stnpca.*",netapp_cluster!="brazilstorec2",aggr!="aggr_sata_sl_00103"}[2h])) > 90
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate full (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate used space > 90%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- if not (index .Values.prometheusRules.disabled "HeadroomAggrCurrentUtilization" | default false) }}
      - alert: HeadroomAggrCurrentUtilization
        expr: (avg_over_time(headroom_aggr_current_utilization{netapp_cluster!~".*root.*"}[2h])) > 90
        for: 5m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_aggr
        annotations:
          summary: Aggregate headroom current utilization (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Aggregate headroom current utilization > 90%
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.netapp_cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

{{- end }}
{{- end }}
{{- end }}
