# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
{{- if ne (.Values.prometheusRules.ruleGroups.netappClusterAlerts | toString) "false" }}
groups:
  - name: netapp_cluster_alerts
    rules:
      - alert: ClusterSwitchPortCRCerrors
        expr: (ems_events{message="vifmgr.cluscheck.hwerrors"})
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_cluster_switch
        annotations:
          summary: Cluster switch port CRC errors (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Cluster switch port CRC errors
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

      - alert: ClusterSwitchReboot
        expr: (ems_events{message="cluster.switch.reboot"})
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_cluster_switch
        annotations:
          summary: Cluster switch reboot (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            Cluster switch reboot
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

      - alert: SecdRpcServerRequestDropped
        expr: (ems_events{message="secd.rpc.server.request.dropped"})
        for: 5m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_cluster_switch
        annotations:
          summary: RPC dropped due to lack of memory (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            This message occurs when an RPC is dropped by SecD due to memory exhaustion.
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}

      - alert: OntapUpgradePauseEvent
        expr: (ems_events{message="upgrademgr.update.pausedErr"})
        for: 5m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "dme-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_cluster_switch
        annotations:
          summary: ONTAP upgrade paused due to error (instance {{ "{{" }} $labels.instance {{ "}}" }})
          description: |
            The automated cluster update has been paused due to an error.
            VALUE = {{ "{{" }} $value {{ "}}" }}
            Cluster: {{ "{{" }} $labels.cluster {{ "}}" }}, Node: {{ "{{" }} $labels.node {{ "}}" }}, Datacenter: {{ "{{" }} $labels.datacenter {{ "}}" }}
{{- else }}
groups: []
{{- end }}
