# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
{{- if ne (.Values.prometheusRules.ruleGroups.pvcUsageAlerts | toString) "false" }}
groups:
  - name: pvc-usage-alerts
    rules:
      - alert: PrometheusPVCUsageWarning
        expr: |
          (
            kubelet_volume_stats_used_bytes{persistentvolumeclaim=~".*prometheus-kube-monitoring.*", cluster=~".*dme-forge.*"}
            /
            kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~".*prometheus-kube-monitoring.*", cluster=~".*dme-forge.*"}
          ) * 100 > 75
        for: 1m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "sci-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: pvc_usage
        annotations:
          summary: "PVC is more than 75% full for Prometheus"
          description: 'PVC {{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} $value | printf "%.2f" {{ "}}" }}% full.'

      - alert: PrometheusPVCUsageCritical
        expr: |
          (
            kubelet_volume_stats_used_bytes{persistentvolumeclaim=~".*prometheus-kube-monitoring.*", cluster=~".*dme-forge.*"}
            /
            kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~".*prometheus-kube-monitoring.*", cluster=~".*dme-forge.*"}
          ) * 100 > 85
        for: 1m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "sci-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: pvc_usage
        annotations:
          summary: "PVC is more than 85% full for Prometheus"
          description: 'PVC {{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} $value | printf "%.2f" {{ "}}" }}% full.'

      - alert: ThanosCompactorPVCUsageWarning
        expr: |
          (
            kubelet_volume_stats_used_bytes{persistentvolumeclaim=~"thanos-compactor", cluster=~".*dme-forge.*"}
            /
            kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"thanos-compactor", cluster=~".*dme-forge.*"}
          ) * 100 > 75
        for: 1m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "sci-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: pvc_usage
        annotations:
          summary: "PVC is more than 75% full for Thanos Compactor"
          description: 'PVC {{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} $value | printf "%.2f" {{ "}}" }}% full.'

      - alert: ThanosCompactorPVCUsageCritical
        expr: |
          (
            kubelet_volume_stats_used_bytes{persistentvolumeclaim=~"thanos-compactor", cluster=~".*dme-forge.*"}
            /
            kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"thanos-compactor", cluster=~".*dme-forge.*"}
          ) * 100 > 85
        for: 1m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "sci-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: pvc_usage
        annotations:
          summary: "PVC is more than 85% full for Thanos Compactor"
          description: 'PVC {{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} $value | printf "%.2f" {{ "}}" }}% full.'

      - alert: GrafanaPVCUsageWarning
        expr: |
          (
            kubelet_volume_stats_used_bytes{persistentvolumeclaim=~"storage-grafana-0"}
            /
            kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"storage-grafana-0"}
          ) * 100 > 75
        for: 1m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "sci-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: pvc_usage
        annotations:
          summary: "PVC is more than 75% full for Grafana"
          description: 'PVC {{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} $value | printf "%.2f" {{ "}}" }}% full.'

      - alert: GrafanaPVCUsageCritical
        expr: |
          (
            kubelet_volume_stats_used_bytes{persistentvolumeclaim=~"storage-grafana-0"}
            /
            kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"storage-grafana-0"}
          ) * 100 > 85
        for: 1m
        labels:
          severity: critical
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "sci-storage" (.Values.prometheusRules.commonLabels | default dict) }}
          component: pvc_usage
        annotations:
          summary: "PVC is more than 85% full for Grafana"
          description: 'PVC {{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} $value | printf "%.2f" {{ "}}" }}% full.'
{{- else }}
groups: []
{{- end }}
