{
 "title": "Alertmanager",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [ "alertmanager " ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alertmanager_build_info, namespace)"
    }
   },
   {
    "name": "alertmanager",
    "label": "alertmanager",
    "query": {
     "query": "label_values(alertmanager_build_info{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "alertmanagerPod",
    "label": "alertmanagerPod",
    "query": {
     "query": "label_values(alertmanager_build_info{namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (version) (alertmanager_build_info{job=~\"alerts-$alertmanager\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Time since last successful config reload",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{job=~\"alerts-$alertmanager\"}"
    }
   ]
  },
  {
   "title": "Time since last successful config reload",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_config_last_reload_successful{job=~\"alerts-$alertmanager\"})"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "singlestat",
   "description": "Number of peers in the Alertmanager cluster.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_cluster_members{job=~\"alerts-$alertmanager\"})"
    }
   ]
  },
  {
   "title": "Number of active alerts",
   "type": "singlestat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", job=~\"alerts-$alertmanager\"})"
    }
   ]
  },
  {
   "title": "Number of suppressed alerts",
   "type": "singlestat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\", job=~\"alerts-$alertmanager\"})"
    }
   ]
  },
  {
   "title": "Number of active silences",
   "type": "singlestat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\", job=~\"alerts-$alertmanager\"})"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Notifications sent from alertmanager-$alertmanager",
   "type": "graph",
   "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "repeat": "alertmanager",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total{job=~\"alerts-$alertmanager\"}[5m])) by (receiver_name)",
     "legendFormat": "{{ receiver_name }}"
    },
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{jobs=~\"alerts-$alertmanager\"}[5m])) by (receiver_name)      ",
     "legendFormat": "Failed {{ receiver_name }}"
    }
   ]
  },
  {
   "title": "Notification durations per integration on alertmanager-$alertmanager",
   "type": "graph",
   "description": "Duration of notification sends in 0.99 and 0.9 quantiles per integration.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "repeat": "alertmanager",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.9,rate(alertmanager_notification_latency_seconds_bucket{job=~\"alerts-$alertmanager\"}[5m]))) by (receiver_name)",
     "legendFormat": "0.9q {{ receiver_name }}"
    },
    {
     "expr": "sum(histogram_quantile(0.99,rate(alertmanager_notification_latency_seconds_bucket{job=~\"alerts-$alertmanager\"}[5m]))) by (receiver_name)",
     "legendFormat": "0.99q  {{ receiver_name }}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active alerts in alertmanager-$alertmanager",
     "type": "graph",
     "description": "Number of alerts by state such as `active`, `suppressed` etc.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(alertmanager_alerts{job=~\"alerts-$alertmanager\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Received alerts by status for alertmanager-$alertmanager",
     "type": "graph",
     "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(alertmanager_alerts_received_total{job=~\"alerts-$alertmanager\"}[5m])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusterhealth score for alertmanger-$alertmanager",
     "type": "graph",
     "description": "Shows cluster score representing cluster health. From Hashicorps official documentation: \n> This metric describes a node's perception of its own health based on how well it is meeting the soft real-time requirements of the protocol. This metric ranges from 0 to 8, where 0 indicates \"totally healthy\".\n\nFor more info see https://www.consul.io/docs/agent/telemetry.html#cluster-health",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alertmanager_cluster_health_score{job=~\"alerts-$alertmanager\"}",
       "legendFormat": "Cluster health score"
      }
     ]
    },
    {
     "title": "Cluster members count on alertmanger-$alertmanager",
     "type": "graph",
     "description": "Shows gossip cluster members count in time and failing peers in case of any in red color.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alertmanager_cluster_members{job=~\"alerts-$alertmanager\"}",
       "legendFormat": "Number of cluster members"
      },
      {
       "expr": "alertmanager_cluster_failed_peers{job=~\"alerts-$alertmanager\"}",
       "legendFormat": "Number of failed peers"
      }
     ]
    },
    {
     "title": "Cluster peers left/joined on alertmanger-$alertmanager",
     "type": "graph",
     "description": "On positive axis shows number of peers that joined the cluster and on negative axis number of peers that left the cluster.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_peers_left_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Cluster joined peers"
      },
      {
       "expr": "increase(alertmanager_cluster_peers_joined_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Cluster left peers"
      }
     ]
    },
    {
     "title": "Cluster reconnections on alertmanger-$alertmanager",
     "type": "graph",
     "description": "On positive axis is number of attempts to reconnect the cluster. On negative axis if number of failed attempts.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_reconnections_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Sucessful reconnections"
      },
      {
       "expr": "increase(alertmanager_cluster_reconnections_failed_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Failed reconnections"
      }
     ]
    },
    {
     "title": "Cluster messages count on alertmanger-$alertmanager",
     "type": "graph",
     "description": "On positive axis is number of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_total{job=~\"alerts-$alertmanager\"}[5m])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_total{job=~\"alerts-$alertmanager\"}[5m])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages size on alertmanger-$alertmanager",
     "type": "graph",
     "description": "On positive axis is size of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_size_total{job=~\"alerts-$alertmanager\"}[5m])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_size_total{job=~\"alerts-$alertmanager\"}[5m])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages queue on alertmanger-$alertmanager",
     "type": "graph",
     "description": "On positive axis is number of queued cluster messages and on negative axis number of pruned messages.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alertmanager_cluster_messages_pruned_total{job=~\"alerts-$alertmanager\"}",
       "legendFormat": "Pruned messaged"
      },
      {
       "expr": "alertmanager_cluster_messages_queued{job=~\"alerts-$alertmanager\"}",
       "legendFormat": "Queued messages"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of oversized gossip messages on alertmanger-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_oversized_gossip_message_sent_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_dropped_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "dropped {{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_failure_total{job=~\"alerts-$alertmanager\"}[$__interval])",
       "legendFormat": "failed {{key}}"
      }
     ]
    },
    {
     "title": "Duration of oversized gossip messages on alertmanger-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_oversize_gossip_message_duration_seconds_bucket{job=~\"alerts-$alertmanager\"}[5m]))",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Number of  propagated gossip messages on alertmanger-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_silences_gossip_messages_propagated_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "silences"
      },
      {
       "expr": "increase(alertmanager_nflog_gossip_messages_propagated_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "nf_log"
      }
     ]
    }
   ]
  },
  {
   "title": "Nflog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nf log queries count for alertmanger-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_nflog_queries_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Nf log query count"
      },
      {
       "expr": "increase(alertmanager_nflog_query_errors_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Nf log query errors"
      }
     ]
    },
    {
     "title": "Nf log query duration for alertmanger-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_nflog_query_duration_seconds_bucket{job=~\"alerts-$alertmanager\"}[5m]))",
       "legendFormat": "Nf log query duration"
      }
     ]
    },
    {
     "title": "Nf log snapshot size for alertmanger-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "alertmanager_nflog_snapshot_size_bytes{job=~\"alerts-$alertmanager\"}",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    },
    {
     "title": "Nf log snapshot duration for alertmanger-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_snapshot_duration_seconds_sum{job=~\"alerts-$alertmanager\"}[5m]) / rate(alertmanager_nflog_snapshot_duration_seconds_sum{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    },
    {
     "title": "Avg Nf log Go GC time for alertmanger-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_gc_duration_seconds_sum{job=~\"alerts-$alertmanager\"}[5m]) / \nrate(alertmanager_nflog_gc_duration_seconds_count{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Cluster joined peers"
      }
     ]
    }
   ]
  },
  {
   "title": "Silences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Silences count by state on alertmanager-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alertmanager_silences{job=~\"alerts-$alertmanager\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Silences query count on alertmanager-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_silences_queries_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Silecnces query count"
      },
      {
       "expr": "increase(alertmanager_silences_query_errors_total{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Silecnces query fails"
      }
     ]
    },
    {
     "title": "Silences query duration on alertmanager-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_silences_query_duration_seconds_bucket{job=~\"alerts-$alertmanager\"}[5m]))",
       "legendFormat": "Silecnces query duration"
      }
     ]
    },
    {
     "title": "Silences snapshot size on alertmanager-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_size_bytes{job=~\"alerts-$alertmanager\"}",
       "legendFormat": "Silecnces snapshot size"
      }
     ]
    },
    {
     "title": "Silences snapshot duration on alertmanager-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(alertmanager_silences_snapshot_duration_seconds_sum{job=~\"alerts-$alertmanager\"}[5m]) /\nrate(alertmanager_silences_snapshot_duration_seconds_count{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Silecnces snapshot duration"
      }
     ]
    },
    {
     "title": "Silences GC duraton on alertmanager-$alertmanager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(alertmanager_silences_gc_duration_seconds_count{job=~\"alerts-$alertmanager\"}[5m])",
       "legendFormat": "Silecnces GC  duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage/s for $alertmanagerPod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, container) (rate(container_cpu_usage_seconds_total{pod=~\"$alertmanagerPod\"}[5m]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{container}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory usage for $alertmanagerPod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "repeat": "alertmanager",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"$alertmanagerPod\", container!=\"\"}) by (namespace, pod, container)",
       "legendFormat": "{{ container }}"
      }
     ]
    }
   ]
  }
 ]
}