
apiVersion: greenhouse.sap/v1alpha1
kind: PluginDefinition
metadata:
  name: blackbox-exporter
spec:
  version: 0.3.0
  displayName: Blackbox exporter
  description: The blackbox exporter allows blackbox probing of endpoints over HTTP, HTTPS, DNS, TCP, ICMP and gRPC.
  # icon: https://raw.githubusercontent.com/cloudoperators/greenhouse-extensions/main/logs/logo.png
  helmChart:
    name: blackbox-exporter
    repository: oci://keppel.global.cloud.sap/charts
    version: 0.3.0
  options:
    - default: 2
      description: Replica count of blackbox exporter deployment
      name: blackbox-exporter.replicas
      required: false
      type: int
    - description: Resource limits
      name: blackbox-exporter.resources
      required: false
      type: map
      default:
        limits:
          memory: 256Mi
        requests:
          cpu: 0.5
          memory: 256Mi
