# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
validate-maintainers: true
check-version-increment: true
skip-clean-up: true
namespace: default
release-label: "app.kubernetes.io/instance"
chart-dirs:
  - absent-metrics-operator
  - alerts
  - audit-logs
  - blackbox-exporter
  - cert-manager
  - exposed-services/charts/v2.0.0
  - gatekeeper
  - kafka
  - kube-monitoring
  - kubeconfig-generator
  - logs
  - logshipper
  - oidc-discovery-access/charts/1.0.0
  - opensearch
  - perses
  - service-proxy/charts/1.0.0
  - thanos
  - trust-manager
chart-repos:
  - alerts=https://prometheus-community.github.io/helm-charts
  - audit-logs=https://open-telemetry.github.io/opentelemetry-helm-charts
  - blackbox-exporter=https://prometheus-community.github.io/helm-charts
  - cert-manager=https://charts.jetstack.io
  - gatekeeper=https://open-policy-agent.github.io/gatekeeper/charts
  - kafka=https://strimzi.io/charts
  - kube-monitoring=https://prometheus-community.github.io/helm-charts
  - kubernetes-operations=https://cloudoperators.github.io/kubernetes-operations
  - logs=https://open-telemetry.github.io/opentelemetry-helm-charts
  - logshipper=https://fluent.github.io/helm-charts
  - opensearch=https://opensearch-project.github.io/opensearch-k8s-operator
  - perses=https://perses.github.io/helm-charts
  - thanos=https://thanos-community.github.io/helm-charts/
  - trust-manager=https://charts.jetstack.io