FROM --platform=${BUILDPLATFORM:-linux/amd64} bats/bats:1.11.1

ARG KUBECTL_VERSION=v1.30.3
ARG GRPC_CURL_VERSION=1.9.3

# Add packages
RUN apk upgrade --no-cache --no-progress \  
&& apk --no-cache --no-progress add curl git bash \  
&& apk del --no-cache --no-progress apk-tools alpine-keys

# Install kubectl binary
RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/${BUILDPLATFORM:-linux/amd64}/kubectl" && \
	chmod +x kubectl && \
	mv kubectl /usr/local/bin/

# Add grpcurl installation
RUN curl -L "https://github.com/fullstorydev/grpcurl/releases/download/v$GRPC_CURL_VERSION/grpcurl_${GRPC_CURL_VERSION}_linux_x86_64.tar.gz" | tar -xz && \
    mv grpcurl /usr/local/bin/
