FROM --platform=${BUILDPLATFORM:-linux/amd64} bats/bats:1.12.0@sha256:0257e4f5326dd37046e94d4b8ce07c293447be80a9db6d6dfff1d50d07617e2e

ARG KUBECTL_VERSION=v1.33.1
ARG GRPC_HEALTH_PROBE_VERSION=v0.4.38
ARG YQ_VERSION=v4.45.4

# Add packages
RUN apk upgrade --no-cache --no-progress \  
&& apk --no-cache --no-progress add curl git bash \  
&& apk del --no-cache --no-progress apk-tools alpine-keys

# Install kubectl binary
RUN curl -fLO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# Install GRPC Health Probe
RUN curl -fL https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 -o /usr/local/bin/grpc_health_probe && \
	chmod +x /usr/local/bin/grpc_health_probe

# Install yq binary
RUN curl -fL https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -o /usr/local/bin/yq && \
	chmod +x /usr/local/bin/yq