# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.netappsd.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-monitoring.fullname" . }}-sd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  netappUsername: {{ required ".Values.netappsd.netapp_exporter_user is required" .Values.netappsd.netapp_exporter_user | b64enc | quote }}
  netappPassword: {{ required ".Values.netappsd.netapp_exporter_password is required" .Values.netappsd.netapp_exporter_password | b64enc | quote }}
  netboxToken: {{ required ".Values.netappsd.netbox_api_token is required" .Values.netappsd.netbox_api_token | b64enc | quote }}
  netboxHost: {{ required ".Values.netappsd.netbox_host is required" .Values.netappsd.netbox_host | b64enc | quote }}
{{- end }}