{
 "title": "OpenTelemetry Logs Dashboard",
 "tags": [ "opentelemetry" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": "otel/opentelemetry-collector-logs"
   },
   { "name": "minstep", "label": "Min step", "query": "10s,30s,1m,5m" },
   { "name": "metric", "label": "Base metric", "query": "Rate : rate, Count : increase" },
   {
    "name": "receiver",
    "label": "Receiver",
    "query": {
     "query": "query_result(avg by (receiver) ({__name__=~\"otelcol_receiver_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "processor",
    "label": "Processor",
    "query": {
     "query": "query_result(avg by (processor) ({__name__=~\"otelcol_processor_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "exporter",
    "label": "Exporter",
    "query": {
     "query": "query_result(avg by (exporter) ({__name__=~\"otelcol_exporter_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "grouping",
    "label": "Additional groupping",
    "query": "None (basic metrics) :  , By transport (detailed metrics) : \\,transport, By service instance id : \\,service_instance_id"
   },
   {
    "name": "suffix",
    "label": "Suffix",
    "query": {
     "query": "query_result({__name__=~\"otelcol_process.+\",job=\"$job\"})"
    }
   },
   { "name": "adhoc", "label": "Ad Hoc" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Pod Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=\"otel\"})\n",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Not Shipping Collectors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(kube_pod_status_phase{pod=~\"logs.*\", phase=\"Running\", namespace=\"otel\"})-count(rate(otelcol_exporter_sent_log_records[15m]) > 0)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Failed Pod Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\", namespace=\"otel\"})\n",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Pending Pod Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\", namespace=\"otel\"})\n",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Running Log Collectors",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=~\"logs.*\", phase=\"Running\", namespace=\"otel\"}",
     "legendFormat": "="
    }
   ]
  },
  {
   "title": "Running Operators",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=~\".*operator.*\", phase=\"Running\", namespace=\"otel\"}",
     "legendFormat": "="
    }
   ]
  },
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "<center>\n<a target=\"_blank\" \nhref=\"https://cloudoperators.github.io/greenhouse/docs/\">\nGreenhouse Documentation\n</a> | \n\n<a target=\"_blank\" \nhref=\"https://cloudoperators.github.io/greenhouse/docs/reference/catalog/logs/\">\nGreenhouse Logs Plugin Documentation\n</a> |\n\n<a target=\"_blank\" \nhref=\"https://github.com/cloudoperators/greenhouse-extensions\">\nGreenhouse Extensions GitHub Repository\n</a> | \n\n<a target=\"_blank\" \nhref=\"https://opentelemetry.io/docs/\">\nOpenTelemetry Documentation\n</a> \n</center>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Log Records ${metric:text}",
   "type": "graph",
   "description": "Accepted: count/rate of log records successfully pushed into the pipeline.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_log${suffix}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Refused Log Records ${metric:text}",
   "type": "graph",
   "description": "Refused: count/rate of log records that could not be pushed into the pipeline.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_log${suffix}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text}",
   "type": "graph",
   "description": "Accepted: count/rate of metric points successfully pushed into the pipeline.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_metric${suffix}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Refused Metric Points ${metric:text}",
   "type": "graph",
   "description": "Refused: count/rate of metric points that could not be pushed into the pipeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_metric${suffix}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Batch Metrics 1",
   "type": "graph",
   "description": "Number of times the batch was sent due to a size trigger. Number of times the batch was sent due to a timeout trigger.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_size_trigger${suffix}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Batch sent due to a size trigger: {{processor}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_timeout_trigger${suffix}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Batch sent due to a timeout trigger: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Batch Metrics 2",
   "type": "graph",
   "description": "Sent: count/rate of spans successfully sent to destination.\\nEnqueue: count/rate of spans failed to be added to the sending queue.\nFailed: count/rate of spans in failed attempts to send to destination.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Spans ${metric:text}",
   "type": "graph",
   "description": "Sent: count/rate of metric points successfully sent to destination.\nEnqueue: count/rate of metric points failed to be added to the sending queue.\nFailed: count/rate of metric points in failed attempts to send to destination.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_metric${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_metric${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_metric${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text}",
   "type": "graph",
   "description": "Sent: count/rate of metric points successfully sent to destination.\nEnqueue: count/rate of metric points failed to be added to the sending queue.\nFailed: count/rate of metric points in failed attempts to send to destination.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_metric${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_metric${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_metric${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)"
    }
   ]
  },
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Total RSS Memory",
   "type": "graph",
   "description": "Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys')",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(otelcol_process_runtime_total_sys_memory{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "max(otelcol_process_runtime_total_sys_memory{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_runtime_total_sys_memory{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Total Runtime Sys Memory",
   "type": "graph",
   "description": "Bytes of allocated heap objects (see 'go doc runtime.MemStats.HeapAlloc')",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(otelcol_process_runtime_heap_alloc{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_process_runtime_heap_alloc{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_runtime_heap_alloc{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Total Runtime Heap Memory",
   "type": "graph",
   "description": "Total CPU user and system time in percentage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(otelcol_process_cpu${suffix}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Max CPU usage {{service_instance_id}}"
    },
    {
     "expr": "avg(rate(otelcol_process_cpu${suffix}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Avg CPU usage {{service_instance_id}}"
    },
    {
     "expr": "min(rate(otelcol_process_cpu${suffix}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Min CPU usage {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Total CPU user and system time in percentage",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(rate(otelcol_process_cpu${suffix}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Max CPU usage {{service_instance_id}}"
    },
    {
     "expr": "avg(rate(otelcol_process_cpu${suffix}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Avg CPU usage {{service_instance_id}}"
    },
    {
     "expr": "min(rate(otelcol_process_cpu${suffix}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Min CPU usage {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Service Instance Count",
   "type": "graph",
   "description": "Total CPU user and system time in percentage",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu${suffix}{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id))",
     "legendFormat": "Service instance count"
    }
   ]
  },
  {
   "title": "Uptime by Service Instance",
   "type": "graph",
   "description": "Number of service instances, which are reporting metrics",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(otelcol_process${suffix}{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id,service_name,service_version)",
     "legendFormat": "Service instance uptime: {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Service Instance Details",
   "type": "table",
   "description": "Number of service instances, which are reporting metrics",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "max(otelcol_process${suffix}{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id,service_name,service_version)",
     "legendFormat": "Service instance count"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Pods",
   "type": "graph",
   "description": "Added: Number of pod add events received.\nUpdated: Number of pod update events received.\nDeleted: Number of pod delete events received.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(otelcol_otelsvc_k8s_pod${suffix}{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Deleted: {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(otelcol_otelsvc_k8s_pod${suffix}{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Updated: {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(otelcol_otelsvc_k8s_pod${suffix}{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Added: {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "graph",
   "description": "Added: Number of namespace add events received.\nUpdated: Number of namespace update events received.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(otelcol_otelsvc_k8s_namespace${suffix}{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Updated: {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_otelsvc_k8s_namespace${suffix}{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Added: {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(otelcol_otelsvc_k8s_pod${suffix}{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Added: {{transport}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "RPC server/client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } }
 ]
}