{
 "title": "Prometheus Details",
 "description": "Providing details for all Prometheus but kubernetes",
 "tags": [ "prometheus" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "prometheus",
    "label": "Prometheus",
    "query": {
     "query": "label_values(prometheus_build_info, job)"
    }
   },
   {
    "name": "shortPromName",
    "label": "Prometheus",
    "query": {
     "query": "label_values(prometheus_build_info{job=~\"$prometheus\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (version)(prometheus_build_info{job=\"$prometheus\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Time since last successful config reload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(time() - prometheus_config_last_reload_success_timestamp_seconds{job=~\"$prometheus\"})"
    }
   ]
  },
  {
   "title": "Last config reload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(prometheus_config_last_reload_successful{job=~\"$prometheus\"})"
    }
   ]
  },
  {
   "title": "WAL Corruptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_wal_corruptions_total{job=~\"$prometheus\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"prometheus-$shortPromName-0\", container!=\"\"}) by (namespace, pod, container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, container) (rate(container_cpu_usage_seconds_total{pod=~\"prometheus-$shortPromName-0\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "HTTP server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(prometheus_http_request_duration_seconds_count{job=~\"$prometheus\"}[2m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Timeseries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=~\"$prometheus\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$prometheus\"}",
     "legendFormat": "{{  job }}"
    }
   ]
  },
  {
   "title": "Target Sync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$prometheus\"}[5m])) by (scrape_job) * 1e3",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Top scrape duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds{job=~\"$prometheus\"}) by (job))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Query Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=~\"$prometheus\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=~\"$prometheus\"}",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Reload Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=~\"$prometheus\"}[5m])",
     "legendFormat": "reloads"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=~\"$prometheus\"}[5m])",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Samples Appended",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{job=~\"$prometheus\"}[5m]))",
     "legendFormat": "samples"
    }
   ]
  },
  {
   "title": "Active Appenders",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_active_appenders{job=~\"$prometheus\"})",
     "legendFormat": "active_appenders"
    },
    {
     "expr": "sum(process_open_fds{job=~\"$prometheus\"})",
     "legendFormat": "open_fds"
    }
   ]
  },
  {
   "title": "Rule Group Eval Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_rule_group_duration_seconds{job=~\"$prometheus\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Rule Group Eval Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_rule_group_iterations_missed_total{job=~\"$prometheus\"}[5m]))",
     "legendFormat": "missed"
    },
    {
     "expr": "sum(rate(prometheus_rule_group_iterations_total{job=~\"$prometheus\"}[5m]))",
     "legendFormat": "iterations"
    }
   ]
  },
  {
   "title": "Compaction Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_tsdb_compaction_duration_seconds_bucket{job=~\"$prometheus\"}[5m])) by (le))",
     "legendFormat": "duration-{{p99}}"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_total{job=~\"$prometheus\"}[5m])",
     "legendFormat": "compactions"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_failed_total{job=~\"$prometheus\"}[5m])",
     "legendFormat": "failed"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_triggered_total{job=~\"$prometheus\"}[5m])",
     "legendFormat": "triggered"
    }
   ]
  },
  {
   "title": "Head Block GC Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_gc_duration_seconds{job=~\"$prometheus\",quantile=\"0.99\"}",
     "legendFormat": "duration-p99"
    },
    {
     "expr": "irate(prometheus_tsdb_head_gc_duration_seconds_count{job=~\"$prometheus\"}[5m])",
     "legendFormat": "collections"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=~\"$prometheus\"}",
     "legendFormat": "blocks"
    }
   ]
  }
 ]
}