groups:
  - name: opensearch-guardian
    interval: 30s
    rules:
      - alert: OpenSearchGuardianNoncompliant
        expr: opensearch_guardian_status{cluster="{{ .Values.cluster.cluster.name }}", status="noncompliant"} > 0
        for: 10m
        labels:
          severity: info # critical
          component: opensearch-guardian
          playbook: https://github.com/cloudoperators/greenhouse-extensions/tree/main/opensearch/playbooks/OpenSearchGuardianNoncompliant.md
          {{- include "opensearch-alert-labels" . | nindent 10 }}
        annotations:
          summary: "OpenSearch is NONCOMPLIANT"
          description: "OpenSearch in namespace {{`{{ $labels.namespace }}`}} has been NONCOMPLIANT for more than 10 minutes"
      - alert: OpenSearchGuardianEmpty
        expr: opensearch_guardian_status{cluster="{{ .Values.cluster.cluster.name }}", status="empty"} > 0
        for: 10m
        labels:
          severity: info # critical
          component: opensearch-guardian
          playbook: https://github.com/cloudoperators/greenhouse-extensions/tree/main/opensearch/playbooks/OpenSearchGuardianEmpty.md
          {{- include "opensearch-alert-labels" . | nindent 10 }}
        annotations:
          summary: "OpenSearch has empty Guardian status"
          description: "OpenSearch in namespace {{`{{ $labels.namespace }}`}} has empty Guardian status for more than 10 minutes"
      - alert: OpenSearchGuardianErrors                                                                                                                                            
        expr: increase(opensearch_guardian_errors_total{cluster="{{ .Values.cluster.cluster.name }}"}[10m]) > 0                                                                    
        for: 0m                                                                                                                                                                    
        labels:                                                                                                                                                                    
          severity: info # critical                                                                                                                                                           
          component: opensearch-guardian                                                                                                                                           
          playbook: https://github.com/cloudoperators/greenhouse-extensions/tree/main/opensearch/playbooks/OpenSearchGuardianErrors.md                                                                                                                                                         
          {{- include "opensearch-alert-labels" . | nindent 10 }}                                                                                                                  
        annotations:                                                                                                                                                               
          summary: "OpenSearch Guardian errors detected"                                                                                                                           
          description: "OpenSearch in namespace {{`{{ $labels.namespace }}`}} reported Guardian errors in the last 10 minutes"
      - alert: OpenSearchGuardianStatusStale                                                                                                                                            
        expr: (time() - opensearch_guardian_status{cluster="{{ .Values.cluster.cluster.name }}", status="compliant"} / 1000) > 420 and opensearch_guardian_status{cluster="{{ .Values.cluster.cluster.name }}", status="compliant"} > 0
        for: 0m                                                                                                                                                                    
        labels:                                                                                                                                                                    
          severity: info # critical                                                                                                                                                           
          component: opensearch-guardian                                                                                                                                           
          playbook: https://github.com/cloudoperators/greenhouse-extensions/tree/main/opensearch/playbooks/OpenSearchGuardianStatusStale.md                                                                                                                                                         
          {{- include "opensearch-alert-labels" . | nindent 10 }}                                                                                                                  
        annotations:                                                                                                                                                               
          summary: "OpenSearch Guardian status is stale"                                                                                                                           
          description: "OpenSearch Guardian in namespace {{`{{ $labels.namespace }}`}} has not refreshed status for more than 7 minutes" 
