groups:
  - name: opensearch-operator
    interval: 30s
    rules:
      - alert: OpenSearchOperatorDown
        expr: up{job=~".*opensearch-operator.*", namespace="{{ .Release.Namespace }}"} == 0
        for: 10m
        labels:
          severity: critical
          component: opensearch-operator
          playbook: {{ .Values.cluster.playbooksUrls.opensearchOperatorDown }}
          {{- include "opensearch-alert-labels" . | nindent 10 }}
        annotations:
          summary: "OpenSearch operator is down"
          description: "OpenSearch operator in namespace {{`{{ $labels.namespace }}`}} has been down for more than 10 minutes"
