{
 "title": "OTEL File Collector",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "HTTP Out- Buckets in Milliseconds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_duration_bucket{le=\"25\"}[5m])) - sum(rate(http_client_duration_bucket{le=\"10\"}[5m]))",
     "legendFormat": "10-25"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{le=\"50\"}[5m])) - sum(rate(http_client_duration_bucket{le=\"25\"}[5m]))",
     "legendFormat": "26-50"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{le=\"75\"}[5m])) - sum(rate(http_client_duration_bucket{le=\"50\"}[5m]))",
     "legendFormat": "50-75"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{le=\"100\"}[5m])) - sum(rate(http_client_duration_bucket{le=\"75\"}[5m]))",
     "legendFormat": "75-100"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{le=\"250\"}[5m])) - sum(rate(http_client_duration_bucket{le=\"100\"}[5m]))",
     "legendFormat": "100-250"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{le=\"500\"}[5m])) - sum(rate(http_client_duration_bucket{le=\"250\"}[5m]))",
     "legendFormat": "250-500"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{le=\"750\"}[5m])) - sum(rate(http_client_duration_bucket{le=\"500\"}[5m]))",
     "legendFormat": "500-750"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{le=\"1000\"}[5m])) - sum(rate(http_client_duration_bucket{le=\"750\"}[5m]))",
     "legendFormat": "750-1.000"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{le=\"10000\"}[5m])) - sum(rate(http_client_duration_bucket{le=\"1000\"}[5m]))",
     "legendFormat": "1.000-10.000"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{le=\"+Inf\"}[5m])) - sum(rate(http_client_duration_bucket{le=\"1000\"}[5m]))",
     "legendFormat": ">10.000"
    }
   ]
  },
  {
   "title": "INPUT by TYPE",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (receiver) (rate(otelcol_receiver_accepted_log_records_total[15m]))",
     "legendFormat": "{{events}}"
    }
   ]
  },
  {
   "title": "Log Records",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (k8s_node_name) (rate(otelcol_receiver_accepted_log_records_total[5m]))",
     "legendFormat": "INPUT RATE {{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "Problems ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (nodename) (rate(otelcol_exporter_send_failed_log_records_total[5m]))",
     "legendFormat": "sending failed {{nodename}}"
    },
    {
     "expr": "sum by (nodename) (rate(otelcol_processor_dropped_logs_total[5m]))",
     "legendFormat": "dropped {{nodename}}"
    },
    {
     "expr": "sum by (cluster) (rate(otelcol_exporter_enqueue_failed_log_records_total[5m]))",
     "legendFormat": "queue problem {{nodename}}"
    }
   ]
  },
  {
   "title": "Pods Update/Delete/Add",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (rate(otelcol_otelsvc_k8s_pod_added_total[5m]))",
     "legendFormat": "pods added"
    },
    {
     "expr": "sum by (cluster) (rate(otelcol_otelsvc_k8s_pod_deleted_total[5m]))",
     "legendFormat": "pods deleted"
    },
    {
     "expr": "sum by (cluster) (rate(otelcol_otelsvc_k8s_pod_updated_total[5m]))",
     "legendFormat": "pods updated"
    }
   ]
  }
 ]
}