{{- if .Values.policies.imagesFromApprovedRegistries.enabled }}
# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: gkimagesfromapprovedregistries
spec:
  crd:
    spec:
      names:
        kind: GkImagesFromApprovedRegistries
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedRegistries:
              type: array
              items:
                description: allowed registry prefix
                type: string

  targets:
    - target: admission.k8s.gatekeeper.sh
      code:
        - engine: Rego
          source:
            version: "v1"
            libs:
              - |
{{ include "gatekeeper-config.lib.add_support_labels" . | indent 16 }}
              - |
{{ include "gatekeeper-config.lib.traversal" . | indent 16 }}
            rego: |
              package imagesfromapprovedregistries

              import data.lib.add_support_labels
              import data.lib.traversal

              iro := input.review.object
              containers := traversal.find_container_specs(iro)

              violation contains {"msg": add_support_labels.from_k8s_object(iro, msg)} if {
                  container := containers[_]
                  image := container.image
                  not image_from_approved_registry(image)
                  msg := sprintf("container %q uses an image from an unapproved registry: %s", [container.name, image])
              }

              image_from_approved_registry(image) if {
                  prefix := input.parameters.allowedRegistries[_]
                  startswith(image, prefix)
              }
{{- end }}
