# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.policies.ingressAnnotationsMigration.enabled (or (.Capabilities.APIVersions.Has "constraints.gatekeeper.sh/v1beta1/GkIngressAnnotationsMigration") .Values.tests.enabled) }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkIngressAnnotationsMigration
metadata:
  name: ingress-annotations-migration
  labels:
    severity: 'error'
spec:
  enforcementAction: {{ .Values.policies.ingressAnnotationsMigration.enforcementAction }}
  match:
    kinds:
      - apiGroups: ["networking.k8s.io"]
        kinds: ["Ingress"]
    scope: Namespaced
{{- end }}
