{{- if .Values.policies.highCpuRequests.enabled }}
# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkHighCPURequests
metadata:
  name: high-cpu-requests
  labels:
    severity: 'warning'
spec:
  enforcementAction: {{ .Values.policies.highCpuRequests.enforcementAction }}
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "DaemonSet", "StatefulSet", "ReplicaSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["batch"]
        kinds: ["Job", "CronJob"]
    scope: Namespaced
  parameters:
    maxCpu: 6
{{- end }}
