{{- if .Values.policies.imagesFromApprovedRegistries.enabled }}
# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkImagesFromApprovedRegistries
metadata:
  name: images-from-approved-registries
  labels:
    severity: 'warning'
spec:
  enforcementAction: {{ .Values.policies.imagesFromApprovedRegistries.enforcementAction }}
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "DaemonSet", "StatefulSet", "ReplicaSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["batch"]
        kinds: ["Job", "CronJob"]
    scope: Namespaced
  parameters:
    allowedRegistries:
      {{- toYaml .Values.policies.imagesFromApprovedRegistries.allowedRegistries | nindent 6 }}
{{- end }}
