{{- if .Values.policies.ingressAnnotations.enabled }}
# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkIngressAnnotations
metadata:
  name: ingress-annotations-wrong-prefix
  labels:
    severity: 'info'
spec:
  enforcementAction: {{ .Values.policies.ingressAnnotations.enforcementAction }}
  match:
    kinds:
      - apiGroups: ["networking.k8s.io"]
        kinds: ["Ingress"]
    scope: Namespaced
  parameters:
    hint: 'use the prefix "nginx.ingress.kubernetes.io/" instead (the legacy "ingress.kubernetes.io/" prefix is deprecated)'
    regexes:
      - '^ingress\.kubernetes\.io/'
{{- end }}
