perses:
  serviceMonitor:
    selfMonitor: true
    labels:
      prometheus: monitoring
    selector:
      matchLabels:
        app.kubernetes.io/name: perses
        app.kubernetes.io/instance: perses
