perses:
  serviceMonitor:
    selfMonitor: true
    labels:
      prometheus: monitoring
    selector:
      matchLabels:
        app.kubernetes.io/name: perses
        app.kubernetes.io/instance: perses

greenhouse:
  prometheusRule:
    perses:
      enabled: true
      labels:
        prometheus: kubernetes
    contentSync:
      enabled: true
      labels:
        prometheus: infra-collector
