{{ if .Values.thanos.serviceMonitor.selfMonitor }}
{{ $root := . }}
{{- range $path, $bytes := .Files.Glob "alerts/*.yaml" }}
{{ $fileName := base $path | trimSuffix ".yaml" }}
{{- if hasKey $root.Values.thanos $fileName }}
{{- if not (eq false (index $root.Values.thanos $fileName "enabled")) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "release.name" $root }}-{{ $fileName }}-alerts
  labels:
    {{- include "thanos.labels" $root | nindent 4 }}
    {{- if $root.Values.thanos.serviceMonitor.labels }}
    {{- toYaml $root.Values.thanos.serviceMonitor.labels | nindent 4 }}
    {{- end }}
    thanos-ruler: {{ $root.Values.thanos.ruler.matchLabel | default $root.Release.Name }}
spec:
  {{- $alertSpec := tpl (printf "%s" $bytes) $root | fromYaml }}
  groups:
  {{- range $alertSpec.groups }}
  - name: {{ .name }}
    rules:
    {{- range .rules }}
    {{- if not (has .alert $root.Values.thanos.serviceMonitor.disabledAlerts) }}
    {{- $rule := . }}
    {{- if hasKey $root.Values.thanos.serviceMonitor.alertOverrides .alert }}
    {{- $overrides := index $root.Values.thanos.serviceMonitor.alertOverrides .alert }}
    {{- $_ := merge $overrides $rule.labels }}
    {{- $rule = merge (dict "labels" $overrides) $rule }}
    {{- end }}
    - {{ toYaml $rule | nindent 6 | trim }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
