#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

plugins_catalog_file="docs/catalog.md"
header='Greenhouse catalog
------------------

This following table provides an overview of the currently available Plugins in Greenhouse.

| Plugin | Description | Version |
| -------- | ------- | ------- |'

# Find and package Helm Charts.
echo -e "$header" > $plugins_catalog_file
all_plugins=$(git grep --recursive --files-with-matches -e "kind: Plugin" -- '*plugin.yaml' | sort | uniq ) || true
for plugin in $all_plugins; do
  table_content=$(yq '(.metadata.name,.spec.description,.spec.version)' "$plugin" | tr '\n' '|')
  echo -e "| ${table_content}" >> $plugins_catalog_file
done
