# extra PrometheusRules on top of upstream charts
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml
{{- if and .Values.alerts.defaultRules.create .Values.alerts.defaultRules.rules.alertmanager }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "kube-prometheus-stack.name" . }}-alertmanager.alerts
  labels:
    alertmanager: {{ include "kube-prometheus-stack.name" . }}
    {{- include "kube-prometheus-stack.labels" . | indent 4 }}
    {{- if .Values.alerts.defaultRules.labels }}
    {{- toYaml .Values.alerts.defaultRules.labels | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: alertmanager.alerts
    rules:
    - alert: AlertmanagerClusterMessagesPruned
      expr: rate(alertmanager_cluster_messages_pruned_total{container="alertmanager", namespace="{{ $.Release.Namespace }}"}[5m]) > 0
      for: 10m
      labels:
        severity: warning
        {{- if or .Values.alerts.defaultRules.additionalRuleLabels }}
          {{- with .Values.alerts.defaultRules.additionalRuleLabels }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
      annotations:
        description: 'Alertmanager {{`{{ $labels.alertmanager }}`}} is pruning the message queue and cluster messages are dropped.'
        summary: Alertmanager in HA cluster fails to synchronize

    - alert: AlertmanagerClusterMessagesQueued
      expr: alertmanager_cluster_messages_queued{container="alertmanager", namespace="{{ $.Release.Namespace }}"} != 0
      for: 15m
      labels:
        severity: info
        {{- if or .Values.alerts.defaultRules.additionalRuleLabels }}
          {{- with .Values.alerts.defaultRules.additionalRuleLabels }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
      annotations:
        description: 'Alertmanager {{`{{ $labels.alertmanager }}`}} is queuing cluster messages. This can cause dropping messages because too many are queued.'
        summary: Alertmanager in HA cluster fails to synchronize

    - alert: AlertmanagerInvalidAlerts
      expr: rate(alertmanager_alerts_invalid_total{container="alertmanager", namespace="{{ $.Release.Namespace }}"}[5m]) > 0
      for: 5m
      labels:
        severity: info
        {{- if or .Values.alerts.defaultRules.additionalRuleLabels }}
          {{- with .Values.alerts.defaultRules.additionalRuleLabels }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
      annotations:
        description: 'Alertmanager {{`{{ $labels.alertmanager }}`}} receives invalid alerts and discards them. Check the Alertmanagers log for details.'
        summary: Alertmanager receives invalid alerts.

    - alert: AlertmanagerClusterHealthDegraded
      expr: alertmanager_cluster_health_score{container="alertmanager", namespace="{{ $.Release.Namespace }}"} != 0
      for: 15m
      labels:
        severity: info
        {{- if or .Values.alerts.defaultRules.additionalRuleLabels }}
          {{- with .Values.alerts.defaultRules.additionalRuleLabels }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
      annotations:
        description: 'Alertmanager {{`{{ $labels.alertmanager }}`}} cluster has problems. Check AM logs.'
        summary: Alertmanager cluster health degraded.

    - alert: AlertmanagerPeerReconnectFailed
      expr: rate(alertmanager_cluster_reconnections_failed_total{container="alertmanager", namespace="{{ $.Release.Namespace }}"}[5m]) != 0
      for: 15m
      labels:
        severity: info
        {{- if or .Values.alerts.defaultRules.additionalRuleLabels }}
          {{- with .Values.alerts.defaultRules.additionalRuleLabels }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
      annotations:
        description: 'Alertmanager {{`{{ $labels.alertmanager }}`}} failed to reconnect to its peer. Check AM logs.'
        summary: Alertmanager failed to reconnect to peer.
{{- end }}