# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

auditLogs:
  openSearchLogs:
    failover_username_a: testusera
    failover_password_a: passworda
    failover_username_b: testuserb
    failover_password_b: passwordb
    endpoint: test-endpoint
    index: test
  elastic:
    enabled: false
  cluster: test
  region: test
  logsCollector:
    kafka:
      enabled: true
      brokers:
        - kafka.test.svc.cluster.local:9092
      protocol_version: "3.9.0"
      encoding: otlp_proto
  ingesterCollector:
    enabled: true
    replicas: 1
    prometheus:
      podMonitor:
        enabled: false
    collectors:
      audit:
        enabled: true
        topic: audit
        replicas: 2
        opensearch:
          endpoint: https://opensearch.test.svc.cluster.local:9200
          tls:
            caSecret: opensearch-ca
            caSecretKey: ca.crt
            insecure: true
          failover_username_a: test
          failover_password_a: test
          failover_username_b: test
          failover_password_b: test
