# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

policies:
  highCpuRequests:
    enabled: true
    enforcementAction: dryrun
    maxCpu: 6

  unmanagedPods:
    enabled: true
    enforcementAction: dryrun
    allowedNamePatterns: []

  forbiddenClusterwideObjects:
    enabled: false
    enforcementAction: dryrun
    allowedWebhooks: []

  imagesFromApprovedRegistries:
    enabled: false
    enforcementAction: dryrun
    allowedRegistries: []

  pciForbiddenImages:
    enabled: false
    enforcementAction: dryrun
    patterns: []

  podRequiredLabels:
    enabled: false
    enforcementAction: dryrun
    requiredLabels: []

  podSecurityV2:
    enabled: false
    enforcementAction: dryrun
    allowlist: []

  ingressAnnotations:
    enabled: true
    enforcementAction: dryrun

  ingressAnnotationsMigration:
    enabled: false
    enforcementAction: dryrun

  prometheusScrapeAnnotations:
    enabled: false
    enforcementAction: dryrun

  # requires gatekeeper-doop: helmManifestParserURL must be set
  deprecatedApiVersion:
    enabled: false
    enforcementAction: dryrun
    helmManifestParserURL: ""

  # requires gatekeeper-doop: helmManifestParserURL must be set
  oliLabelsRequired:
    enabled: false
    enforcementAction: dryrun
    helmManifestParserURL: ""
    knownExceptions: []
    excludedNamespaces: []

  # requires gatekeeper-doop: imageCheckerURL must be set
  outdatedImageBases:
    enabled: false
    enforcementAction: dryrun
    imageCheckerURL: ""
    createdAtHeader: ""
    maxAgeDays: 365

  # requires gatekeeper-doop: imageCheckerURL must be set
  vulnerableImages:
    enabled: false
    enforcementAction: dryrun
    imageCheckerURL: ""
    vulnStatusHeader: ""

tests:
  enabled: false
