# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-doop-agent
  labels:
    {{- include "gatekeeper-doop.labels" . | nindent 4 }}
type: Opaque
data:
  swift_password: {{ .Values.swift.password | required ".Values.swift.password is required" | b64enc | quote }}
