# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-helm-manifest-parser
  labels:
    {{- include "gatekeeper-doop.labels" . | nindent 4 }}
    app.kubernetes.io/component: helm-manifest-parser
spec:
  selector:
    {{- include "gatekeeper-doop.labels" . | nindent 4 }}
    app.kubernetes.io/component: helm-manifest-parser
  ports:
    - name: http
      port: 80
      targetPort: http
