# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- range $user := .Values.users }}
{{- if dig "externalPassword" "enabled" false $user }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $user.authentication.password.valueFrom.secretKeyRef.name | default (printf "kafka-user-%s-password" $user.name) }}
  labels:
    {{- include "kafka.labels" $ | nindent 4 }}
type: Opaque
data:
  password: {{ $user.externalPassword.passwordValue | b64enc | quote }}
{{- end }}
{{- end }}
