# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: greenhouse.sap/v1alpha1
kind: PluginDefinition
metadata:
  name: ingress-nginx
spec:
  version: 1.4.0
  displayName: Ingress NGINX
  description: Ingress NGINX controller for Kubernetes
  docMarkDownUrl: https://raw.githubusercontent.com/cloudoperators/greenhouse-extensions/main/ingress-nginx/README.md
  icon: https://raw.githubusercontent.com/cloudoperators/greenhouse-extensions/main/ingress-nginx/logo.png
  helmChart:
    name: ingress-nginx
    repository: oci://registry.k8s.io/ingress-nginx/charts
    version: v4.15.1
  options:
    - name: controller.service.loadBalancerIP
      description: IP address of the associated load balancer.
      required: false
      type: string
    - name: controller.service.externalIPs
      description: External IP addresses of the load balancer service.
      required: false
      type: list
    - name: controller.service.externalTrafficPolicy
      description: Specifies whether the service routes external traffic to node-local or cluster-wide endpoints. May be "Cluster" or "Local".
      default: "Cluster"
      required: false
      type: string
    - name: controller.replicaCount
      description: Replicas of the ingress controller
      default: 3
      required: false
      type: int
    - name: controller.allowSnippetAnnotations
      description: Allow snippet annotations on ingress resources.
      default: "false"
      required: false
      type: string
    - name: controller.scope.enabled
      description: Limit the scope of the controller to a specific namespace
      default: true
      required: false
      type: bool
    - name: controller.ingressClassResource.default
      description: Whether this is the default ingressClass for the cluster
      default: false
      required: false
      type: bool
    - name: controller.ingressClassResource.name
      description: Name of the ingressClass
      default: "nginx"
      required: false
      type: string
    - name: controller.ingressClassResource.controllerValue
      description: Controller-value of the controller that is processing this ingressClass
      default: "k8s.io/ingress-nginx"
      required: false
      type: string
    - name: controller.watchIngressWithoutClass
      description: Whether to watch ingress resources without a class
      default: true
      required: false
      type: bool
    - name: controller.metrics.enabled
      description: Whether to enable metrics on controller
      default: false
      required: false
      type: bool
    - name: controller.metrics.serviceMonitor.enabled
      description: Whether to enable metrics via ServiceMonitor
      default: false
      required: false
      type: bool
    - name: controller.metrics.serviceMonitor.additionalLabels
      description: Additional labels to add service monitor
      required: false
      type: map
    - name: controller.image.registry
      description: Registry for the ingress-nginx controller image
      required: false
      type: string
    - name: controller.image.image
      description: Image name for the ingress-nginx controller
      default: "ingress-nginx/controller"
      required: false
      type: string
    - name: controller.image.tag
      description: Image tag for the ingress-nginx controller
      default: "v1.15.1"
      required: false
      type: string
    - name: controller.image.digest
      description: Image digest for the ingress-nginx controller
      default: "sha256:594ceea76b01c592858f803f9ff4d2cb40542cae2060410b2c95f75907d659e1"
      required: false
      type: string
    - name: controller.image.digestChroot
      description: Image digest for the chroot variant of the ingress-nginx controller
      default: "sha256:af31d00c9d82c612896b380a9003bd36843b7647b98e4588251c66325317bc72"
      required: false
      type: string
