# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: greenhouse.sap/v1alpha1
kind: PluginDefinition
metadata:
  name: heureka-scanner-k8s-assets
spec:
  version: 0.1.3
  displayName: Heureka Scanner for K8s Assets
  description: The scanner discovers and reports Kubernetes assets (pods, containers, images) to Heureka
  helmChart:
    name: k8s-assets-scanner
    repository: oci://ghcr.io/cloudoperators/heureka/charts
    version: 0.1.1
  options:
    - name: scanner.api_token
      description: The API token for authenticating with the Heureka API
      required: true
      type: string
    - name: scanner.heureka_url
      description: The URL of the Heureka API
      required: true
      type: string
    - name: scanner.schedule
      description: The schedule for the Heureka Scanner. Use a cron expression (e.g. "0 * * * *")
      required: false
      type: string
      default: "0 0 * * *"
    - name: scanner.scanner_timeout
      description: Timeout for scanner operations
      required: false
      type: string
      default: "2h"
    - name: scanner.k8s_cluster_name
      required: false
      description: Cluster name
      type: string
    - name: scanner.k8s_cluster_region
      required: false
      description: Cluster region
      type: string
    - name: scanner.service_label
      description: Pod label indicating the service name
      required: false
      type: string
      default: "ccloud/service"
    - name: scanner.support_group_label
      description: Pod label indicating the support group
      required: false
      type: string
      default: "ccloud/support-group"