# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.openstack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: oscloudsyaml
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  clouds.yaml: {{ printf "clouds:\n  openstack:\n    auth:\n      auth_url: %s\n      username: %s\n      password: %s\n      project_name: %s\n      project_domain_name: %s\n      user_domain_name: %s\n    region_name: %s\n    interface: public\n    auth_type: password" .Values.openstack.authURL .Values.openstack.username .Values.openstack.password .Values.openstack.projectName .Values.openstack.projectDomainName .Values.openstack.userDomainName .Values.openstack.regionName | b64enc }}
{{- end }}
