{{/*
# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
*/}}
{{/* This template creates a Kubernetes Secret containing the OpenStack clouds.yaml configuration for the external-dns plugin.
The secret is only created if the openstack.enabled option is set to true in the values.yaml file. */}}

{{- if .Values.openstack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: oscloudsyaml
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: {{ required "openstack.authURL is required when openstack.enabled is true" .Values.openstack.authURL }}
          username: {{ required "openstack.username is required when openstack.enabled is true" .Values.openstack.username }}
          password: {{ required "openstack.password is required when openstack.enabled is true" .Values.openstack.password }}
          user_domain_name: {{ .Values.openstack.userDomainName | default "Default" }}
          project_id: {{ required "openstack.projectID is required when openstack.enabled is true" .Values.openstack.projectID }}
        region_name: {{ required "openstack.regionName is required when openstack.enabled is true" .Values.openstack.regionName }}
        interface: public
        auth_type: password
{{- end }}
