# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- if and (.Capabilities.APIVersions.Has "trust.cert-manager.io/v1alpha1") .Values.bundle.enabled -}}
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: {{ .Values.bundle.name }}
spec:
  sources:
  - useDefaultCAs: true
  - configMap:
      key: ca.crt
      name: kube-root-ca.crt
{{- if and .Values.additionalSources.enabled .Values.additionalSources.sources }}
  {{- .Values.additionalSources.sources | toYaml | nindent 2 }}
{{- end }}
  target:
    configMap:
      key: "trust-bundle.pem"
{{- if .Values.namespaces }}
    namespaceSelector:
      {{- .Values.namespaces | toYaml | nindent 6 }}
{{- end }}
{{- end }}
