
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-recv-deployment
  namespace: app
  labels:
    name: go-recv
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-recv
  template:
    metadata:
      labels:
        name: go-recv
    spec:
      containers:
        - name: load-recv
          image: load-recv:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: load-recv
  namespace: app
spec:
  selector:
    name: go-recv
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080