{{- define "field_normalisation.transform" }}
transform/field-normalisation:
  error_mode: ignore
  log_statements:
    - context: log
      statements:
        - set(log.attributes["auditd.paths"], String(log.attributes["auditd"]["paths"])) where log.attributes["auditd"] != nil and log.attributes["auditd"]["paths"] != nil
        - delete_key(log.attributes["auditd"], "paths") where log.attributes["auditd"] != nil and log.attributes["auditd"]["paths"] != nil
        - set(log.attributes["auditd.data"], String(log.attributes["auditd"]["data"])) where log.attributes["auditd"] != nil and log.attributes["auditd"]["data"] != nil
        - delete_key(log.attributes["auditd"], "data") where log.attributes["auditd"] != nil and log.attributes["auditd"]["data"] != nil
        - set(log.attributes["audit_host"], String(log.attributes["host"])) where log.attributes["host"] != nil
        - delete_key(log.attributes, "host") where log.attributes["host"] != nil
        - set(log.attributes["audit_source_ips"], String(log.attributes["sourceIPs"])) where log.attributes["sourceIPs"] != nil
        - delete_key(log.attributes, "sourceIPs") where log.attributes["sourceIPs"] != nil
        - set(log.attributes["audit_event_category"], String(log.attributes["event.category"])) where log.attributes["event.category"] != nil
        - delete_key(log.attributes, "event.category") where log.attributes["event.category"] != nil
        - set(log.attributes["audit_process"], String(log.attributes["process"])) where log.attributes["process"] != nil
        - delete_key(log.attributes, "process") where log.attributes["process"] != nil
        - set(log.attributes["audit_prometheus"], String(log.attributes["prometheus"])) where log.attributes["prometheus"] != nil
        - delete_key(log.attributes, "prometheus") where log.attributes["prometheus"] != nil
        - set(log.attributes["audit_args"], String(log.attributes["args"])) where log.attributes["args"] != nil
        - delete_key(log.attributes, "args") where log.attributes["args"] != nil
        - set(log.attributes["audit_status"], String(log.attributes["status"])) where log.attributes["status"] != nil
        - delete_key(log.attributes, "status") where log.attributes["status"] != nil
        - set(log.attributes["http_string"], String(log.attributes["log"]["http"])) where log.attributes["http_string"] == nil and log.attributes["log"] != nil and IsString(log.attributes["log"]) == false and log.attributes["log"]["http"] != nil
        - delete_key(log.attributes["log"], "http") where log.attributes["log"] != nil and IsString(log.attributes["log"]) == false and log.attributes["log"]["http"] != nil
        - set(log.attributes["http_string"], String(log.attributes["log.http"])) where log.attributes["http_string"] == nil and log.attributes["log.http"] != nil
        - delete_key(log.attributes, "log.http") where log.attributes["log.http"] != nil
        - set(log.attributes["http_string"], String(log.attributes["log"])) where log.attributes["http_string"] == nil and log.attributes["log"] != nil
        - delete_key(log.attributes, "log") where log.attributes["log"] != nil
        - set(log.attributes["user_agent_string"], String(log.attributes["user_agent"])) where log.attributes["user_agent"] != nil
        - delete_key(log.attributes, "user_agent") where log.attributes["user_agent"] != nil
        - set(log.attributes["user_string"], String(log.attributes["user"])) where log.attributes["user"] != nil
        - delete_key(log.attributes, "user") where log.attributes["user"] != nil
        - set(log.attributes["impersonatedUser_string"], String(log.attributes["impersonatedUser"])) where log.attributes["impersonatedUser"] != nil
        - delete_key(log.attributes, "impersonatedUser") where log.attributes["impersonatedUser"] != nil
        - set(log.attributes["objectRef_string"], String(log.attributes["objectRef"])) where log.attributes["objectRef"] != nil
        - delete_key(log.attributes, "objectRef") where log.attributes["objectRef"] != nil
        - set(log.attributes["k8s_req_payload"], String(log.attributes["requestObject"])) where log.attributes["requestObject"] != nil
        - delete_key(log.attributes, "requestObject") where log.attributes["requestObject"] != nil
        - set(log.attributes["k8s_resp_payload"], String(log.attributes["responseObject"])) where log.attributes["responseObject"] != nil
        - delete_key(log.attributes, "responseObject") where log.attributes["responseObject"] != nil
        - delete_key(log.attributes, "syslog_timestamp") where log.attributes["syslog_timestamp"] != nil and time_unix_nano != 0
        - delete_matching_keys(log.attributes, "^requestObject\\..*")
        - delete_matching_keys(log.attributes, "^responseObject\\..*")
        - delete_matching_keys(log.attributes, "^user\\..*")
        - delete_matching_keys(log.attributes, "^host\\..*")
        - delete_matching_keys(log.attributes, "^sourceIPs\\..*")
        - delete_matching_keys(log.attributes, "^event\\..*")
        - delete_matching_keys(log.attributes, "^process\\..*")
        - delete_matching_keys(log.attributes, "^prometheus\\..*")
        - delete_matching_keys(log.attributes, "^args\\..*")
        - set(log.attributes["context_string"], String(log.attributes["context"])) where log.attributes["context"] != nil
        - delete_key(log.attributes, "context") where log.attributes["context"] != nil
        - delete_matching_keys(log.attributes, "^context\\..*")
        - set(log.attributes["headers_string"], String(log.attributes["headers"])) where log.attributes["headers"] != nil
        - delete_key(log.attributes, "headers") where log.attributes["headers"] != nil
        - delete_matching_keys(log.attributes, "^headers\\..*")
        - set(log.attributes["tags_string"], String(log.attributes["tags"])) where log.attributes["tags"] != nil
        - delete_key(log.attributes, "tags") where log.attributes["tags"] != nil
        - delete_matching_keys(log.attributes, "^tags\\..*")
        - set(log.attributes["tenant_ids_string"], String(log.attributes["tenant_ids"])) where log.attributes["tags"] != nil
        - delete_key(log.attributes, "tenant_ids") where log.attributes["tenant_ids"] != nil
        - delete_matching_keys(log.attributes, "^tenant_ids\\..*")
{{- end }}
