# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.auditLogs.logsCollector.enabled (not .Values.auditLogs.logsCollector.kafka.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: audit-logs-basic-auth
  labels:
  {{- include "plugin.labels" . | nindent 4 }}
  {{- if .Values.auditLogs.customLabels }}
  {{ toYaml .Values.auditLogs.customLabels | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  failover_username_a: {{ required "auditLogs.openSearchLogs.failover_username_a is required when OpenSearch output is enabled" .Values.auditLogs.openSearchLogs.failover_username_a | quote }}
  failover_password_a: {{ required "auditLogs.openSearchLogs.failover_password_a is required when OpenSearch output is enabled" .Values.auditLogs.openSearchLogs.failover_password_a | quote }}
  failover_username_b: {{ required "auditLogs.openSearchLogs.failover_username_b is required when OpenSearch output is enabled" .Values.auditLogs.openSearchLogs.failover_username_b | quote }}
  failover_password_b: {{ required "auditLogs.openSearchLogs.failover_password_b is required when OpenSearch output is enabled" .Values.auditLogs.openSearchLogs.failover_password_b | quote }}
{{- end }}
